import { Patient } from "./types";

export const mockPatients: Patient[] = [
  {
    id: "P001",
    name: "Amina Hassan",
    age: 34,
    gender: "female",
    status: "admitted",
    ward: "cardiology",
    admittedDate: "2025-04-28",
    condition: "Hypertensive crisis",
    doctor: "Dr. Okello",
    bedNumber: "C-04",
  },
  {
    id: "P002",
    name: "James Odhiambo",
    age: 58,
    gender: "male",
    status: "critical",
    ward: "emergency",
    admittedDate: "2025-05-03",
    condition: "Acute myocardial infarction",
    doctor: "Dr. Njeri",
    bedNumber: "E-01",
  },
  {
    id: "P003",
    name: "Fatuma Mbeki",
    age: 27,
    gender: "female",
    status: "observation",
    ward: "general",
    admittedDate: "2025-05-02",
    condition: "Severe dehydration",
    doctor: "Dr. Okello",
    bedNumber: "G-12",
  },
  {
    id: "P004",
    name: "Emmanuel Kariuki",
    age: 45,
    gender: "male",
    status: "admitted",
    ward: "orthopedics",
    admittedDate: "2025-04-30",
    condition: "Fractured femur",
    doctor: "Dr. Abubakar",
    bedNumber: "O-07",
  },
  {
    id: "P005",
    name: "Grace Mwangi",
    age: 9,
    gender: "female",
    status: "admitted",
    ward: "pediatrics",
    admittedDate: "2025-05-01",
    condition: "Pneumonia",
    doctor: "Dr. Njeri",
    bedNumber: "P-03",
  },
  {
    id: "P006",
    name: "Ibrahim Salim",
    age: 63,
    gender: "male",
    status: "discharged",
    ward: "neurology",
    admittedDate: "2025-04-22",
    condition: "Ischemic stroke",
    doctor: "Dr. Abubakar",
    bedNumber: "N-09",
  },
  {
    id: "P007",
    name: "Zawadi Kimani",
    age: 31,
    gender: "female",
    status: "observation",
    ward: "general",
    admittedDate: "2025-05-03",
    condition: "Suspected appendicitis",
    doctor: "Dr. Okello",
    bedNumber: "G-05",
  },
  {
    id: "P008",
    name: "Peter Otieno",
    age: 52,
    gender: "male",
    status: "critical",
    ward: "emergency",
    admittedDate: "2025-05-04",
    condition: "Respiratory failure",
    doctor: "Dr. Njeri",
    bedNumber: "E-02",
  },
  {
    id: "P009",
    name: "Neema Juma",
    age: 41,
    gender: "female",
    status: "admitted",
    ward: "cardiology",
    admittedDate: "2025-04-29",
    condition: "Arrhythmia",
    doctor: "Dr. Abubakar",
    bedNumber: "C-11",
  },
  {
    id: "P010",
    name: "Samuel Wekesa",
    age: 76,
    gender: "male",
    status: "discharged",
    ward: "orthopedics",
    admittedDate: "2025-04-15",
    condition: "Hip replacement recovery",
    doctor: "Dr. Okello",
    bedNumber: "O-02",
  },
];